### ISSUE TITLE
ffmpeg可以编译全版本的吗？ndk18都不支持armeabiv5了，希望把armeabiv7,v8的so编译出来

### ISSUE THREAD

**Issue by lingchen52** [s949492225/iiplayer#1]

**Comment by s949492225** [comment]
ffmpeg是独立的so,我没有做任何的修改,如果你想编译的全版本的话,可以自己去编译,然后加上去就可以了,
你可以用ndk17去编译这个so,我对ffmpeg编译也不是很熟悉,我只会用ndk17以下的编译,18我还没成功过

**Comment by s949492225** [comment]
建议你用最新版本的ffmpeg编译,3的话我发现它内部是有一些bug的

**Comment by s949492225** [comment]
我刚刚把编译的脚本上传了,你最好用15-17版本的ndk编译,否则应该编译不过,注意脚本内的ndk相关的,需要你改成你自己的路径
